# Generated by Django 4.1.2 on 2022-10-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biletlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('optionA', models.CharField(max_length=255)),
                ('optionB', models.CharField(max_length=255)),
                ('optionC', models.CharField(blank=True, max_length=255, null=True)),
                ('optionD', models.CharField(blank=True, max_length=255, null=True)),
                ('optionE', models.CharField(blank=True, max_length=255, null=True)),
                ('correct', models.CharField(max_length=255)),
                ('bilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_bilet', to='main.biletlar')),
            ],
        ),
    ]
